# Generated by Django 5.1 on 2024-08-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='last_modifed_by',
            new_name='last_modified_by',
        ),
    ]
